name: dockerlogin

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  Logintodockerhub:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      uses: docker/login-action@v2.1.0
      with:
       username: ${{secrets.DOCKERHUBUSERNAME}}
       password: ${{secrets.DOCKERHUBPASSWORD}}
    - name: Docker Pull
      run: docker pull python
    - name: Docker Tag
      run: docker tag python ghost421/python-devops
    - name: Docker Push
      run: docker push ghost421/python-devops


  Logintodockerhub_Qa:
    runs-on: ubuntu-latest
    environment: Qa
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      uses: docker/login-action@v2.1.0
      with:
       username: ${{secrets.DOCKERHUBUSERNAME}}
       password: ${{secrets.DOCKERHUBPASSWORD}}
       
